### ISSUE TITLE
Pest 2.1 performance regression

### ISSUE THREAD

**Issue by ralfbiedert** [pest-parser/pest#383] opened 2019-03-10 12:25 UTC
I have a similar problem to #279 and #378 on Pest 2.1, and there seems to be a massive performance regression from previous versions of Pest in my code base between 2.1 and 2.0.

Previously I could load models with 1000s lines from debugging builds practically instantly. Since I switched to 2.1, the same models take "infinitely" long (I run out of patience after a few minutes).

One observation I made is that the length of the whole file seems to affect the time it takes to parse individual lines. In a simple test where I `println!` within `for line in parsed.into_inner() {}`, the speed between printed lines varies with the number of total lines.

Running Instruments, I get the following profiler output:

```
7.84 s  100.0%	0 s	 	                          ffsvm::parser::_$LT$impl$u20$core..convert..TryFrom$LT$$RF$$u27$a$u20$str$GT$$u20$for$u20$ffsvm..parser..raw..ModelFile$LT$$u27$a$GT$$GT$::try_from::h18a6cfd922c8ed7c
7.84 s   99.9%	0 s	 	                           _$LT$pest..iterators..pairs..Pairs$LT$$u27$i$C$$u20$R$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h09b47153f8ca7064
7.83 s   99.9%	0 s	 	                            _$LT$pest..iterators..pairs..Pairs$LT$$u27$i$C$$u20$R$GT$$GT$::peek::hd5e391ef9b3bd4a5
7.82 s   99.7%	1.17 s	 	                             pest::iterators::pair::new::h6f918a45a21ac4ca
5.12 s   65.2%	154.00 ms	 	                              core::str::_$LT$impl$u20$str$GT$::get::h8e194b7c827218ed
4.96 s   63.2%	340.00 ms	 	                               core::str::traits::_$LT$impl$u20$core..slice..SliceIndex$LT$str$GT$$u20$for$u20$core..ops..range..RangeFrom$LT$usize$GT$$GT$::get::hb7a80d56daccaebf
2.91 s   37.1%	841.00 ms	 	                                core::str::_$LT$impl$u20$str$GT$::is_char_boundary::heba54db0f6b30891
1.46 s   18.6%	135.00 ms	 	                                 core::slice::_$LT$impl$u20$$u5b$T$u5d$$GT$::get::h6ea878e5fd88bc3c
559.00 ms    7.1%	223.00 ms	 	                                 core::str::_$LT$impl$u20$str$GT$::len::hdc7068d95f08cfc7
45.00 ms    0.5%	45.00 ms	 	                                 core::str::_$LT$impl$u20$str$GT$::as_bytes::hb983c1a31bd2996f
7.00 ms    0.0%	0 s	 	                                 <Unknown Address>
1.68 s   21.4%	397.00 ms	 	                                core::str::traits::_$LT$impl$u20$core..slice..SliceIndex$LT$str$GT$$u20$for$u20$core..ops..range..RangeFrom$LT$usize$GT$$GT$::get_unchecked::h555020fa357d7a96
28.00 ms    0.3%	0 s	 	                                <Unknown Address>
```

Navigating there in Instruments gives these lines:

```
// TODO(safety): QueueableTokens must be valid indices into input.
pub fn new<R: RuleType>(queue: Rc<Vec<QueueableToken<R>>>, input: &str, start: usize) -> Pair<R> {
    if cfg!(debug_assertions) {
        for tok in queue.iter() {
            match *tok {
                QueueableToken::Start { input_pos, .. } | QueueableToken::End { input_pos, .. } => {
                    assert!(
                        input.get(input_pos..).is_some(),
                        "💥 UNSAFE `Pair` CREATED 💥"
                    )
                }
            }
        }
    }
```
(This code might or might not be related to the actual problem, just providing the output I got.)

Similarly to #378 the speed gets _dramatically_ faster if I run with `--release`. Unfortunately this is not a solution for me, because in dependent projects I have many unit tests with "larger" files to be parsed on `cargo test`, which now all timeout.

**Comment by ralfbiedert** [comment] 2019-03-10 12:55
**Update** - I [pushed a branch](https://github.com/ralfbiedert/ffsvm-rust/tree/pest_performance) that exhibits the problem when running `cargo test`. The test `svm_parsing::load_large` loads a 200k text file and takes forever.

**Comment by CAD97** [comment] 2019-03-10 15:59
Yep, this is a pretty expensive correctness check.

As a temporary workaround, you can disable debug assertions on the test/debug profile to get the faster path.

cc #301

**Comment by CAD97** [comment] 2019-03-10 16:14
By pretty expensive, I mean that every time this path to create a tree ref (`Pair`) is used, the debug assertion iterates the full tree to make sure that none of the indexes are outside the source string. When I added it I didn't realize this would be a hot path.

Removing the check is just a matter of a) going back to trusting or b) properly tracing the dependencies such that there's no chance of breaking safety invariants in safe code.

**Comment by birkenfeld** [comment] 2019-04-14 10:51
Ping. This prevents me from using my create in debug mode, which is a bit inconvenient...

**Comment by CAD97** [comment] 2019-04-14 14:41
You should be [able to do](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections)

```
[profile.dev]
debug-assertions = false
```

and that will disable the checks as a workaround for now. I don't have much time to work on pest right now and dragostis is spending his limited time experimenting with v3, so unfortunately it might be a while before we can attack this correctness assertion.

**Comment by birkenfeld** [comment] 2019-04-14 15:46
AFAIU you could just remove the assertion for now? Its addition is a clear regression, so a revert would make sense until you have figured out a suitable replacement.

**Comment by dragostis** [comment] 2019-04-14 17:10
@birkenfeld, does `debug-assertions = false` solve this?

**Comment by ralfbiedert** [comment] 2019-04-14 17:26
For applications this might just work, but not for libraries.  

In my case I provide a model loader that might be embedded in other libraries, which, in turn, might be embedded in even other libraries or applications. 

Unless I'm missing something all upstream users would have to transitively set (and each in turn communicate upstream to set) `debug-assertions = false`. Some of those might even rely on debug assertions themselves.

**Comment by dragostis** [comment] 2019-04-14 17:48
@ralfbiedert, very good point. We should find a solution on our side and do a point release. Is reverting back to trusting tertiary code a fine trade-off?

**Comment by CAD97** [comment] 2019-04-14 17:59
I'm fine with removing the debug_assert so long as a comment remains reminding us that the code is relying on weakly enforced guarantees. #301 can continue to track the improvement (though i suppose as v3 will retire the `Pairs` API, it will be automatically outdated then).

**Comment by CAD97** [comment] 2019-04-14 18:27
As it turns out, there wasn't much left to remove this fake safety. #388 and a point release should be all we need.

**Comment by CAD97** [comment] 2019-04-14 18:41
I'm going to leave this open until @dragostis pushes the new version.

**Comment by birkenfeld** [comment] 2019-04-14 18:55
> Sorry it took so long to address!

On the other hand, thanks for the quick turnaround!

**Comment by CAD97** [comment] 2019-04-15 21:47
`pest:2.1.1` is released which has the fix for this regression.

**Closed by CAD97** 2019-04-15 21:47 UTC
