### ISSUE TITLE
Feature Request: Add Non-Rust Parser to Chart on Website

### ISSUE THREAD

**Issue by ssokolow** [pest-parser/pest#418] opened 2019-09-23 15:38 UTC
Currently, pest is the slowest parser in the chart on the website. For people who aren't used to thinking in terms of absolute numbers and have no experience with Nom or Serde, that leaves the impression that Pest is slow.

It'd be a good idea to include at least one comparable well-known parser generator from another language on that chart to give people a more intuitive frame of reference. (Something like ANTLR or Parsec)

**Comment by tomtau** [comment] 2022-07-10 07:36
This looks like a duplicate of https://github.com/pest-parser/site/issues/5

**Closed by tomtau** 2022-07-10 07:36 UTC
