### ISSUE TITLE
Hitting OOM error when building large pest file

### ISSUE THREAD

**Issue by negator** [pest-parser/pest#157] opened 2017-09-22 20:38 UTC
I have a large-ish pest file (~ 2600) lines with rules that include large numbers of alternations. When compiling this, the `rustc` process consumes a peak of ~35GB. I assume this has something to do with the optimization step? 

Attaching the file for reference

[entity.pest.zip](https://github.com/pest-parser/pest/files/1325765/entity.pest.zip)

**Comment by dragostis** [comment] 2017-09-22 21:05
I've managed to compile this with less than 200MBs used by rustc. What version of Rust are you using?

**Comment by negator** [comment] 2017-09-22 22:16
Im compiling on a Mac:
```stable-x86_64-apple-darwin (default)
rustc 1.20.0 (f3d6973f4 2017-08-27)```

I've attached a sample project, including a Cargo.toml file which no optimizations. Running `cargo build` and examining the Acitivity Monitor, shows memory usage climb to more than 30GB.

**Comment by negator** [comment] 2017-09-23 00:12
Note this is compressed memory usage. Actual memory usage hits 3-4GB

**Comment by dragostis** [comment] 2017-09-23 12:56
`cargo build` ran with around 300-400MBs:

```
Finished dev [unoptimized + debuginfo] target(s) in 29.8 secs
```

**Comment by dragostis** [comment] 2017-09-23 13:08
I took a look over some recently closed issues in `rustc`, but I wasn't able to where the issue stems from. I would recommend using beta (1.21) until the 12th of October when 1.21 launches. I'll try to look into this soon.

**Comment by Victor-Savu** [comment] 2017-09-24 08:57
Would it make sense to report a bug on the compiler so that it is documented there as well? Especially if the problem was fixed by chance, it points to a potential regression later on.

**Comment by dragostis** [comment] 2017-09-24 11:18
@Victor-Savu Definitely. I've just pushed a feature not so long ago. I'll try to handle this next. (see exactly where the regression might be)

**Comment by negator** [comment] 2017-09-24 17:15
Looks like it was a bug in the rust compiler, https://github.com/rust-lang/rust/issues/43613.

Probably isn't worth looking into further but good to note for reference. 

I'Ill use nightly until rust 1.21 is released. Thanks for the quick responses!

**Comment by dragostis** [comment] 2017-09-24 17:29
Thanks for finding the issue. I'll close this, since the next release of Rust is due to arrive soon anyway.

**Closed by dragostis** 2017-09-24 17:29 UTC
Labels: Difficulty: Hard, Priority: High, Status: Available (not started), Type: Bug
