### ISSUE TITLE
Support for direct left recursive?

### ISSUE THREAD

**Issue by wormtql** [pest-parser/pest#591] opened 2022-04-09 12:05 UTC
In ANTLR, you can have direct left recursive,
```
expression
   : outerAttribute+ expression                         # AttributedExpression // technical, remove left recursive
   | literalExpression                                  # LiteralExpression_
   | pathExpression                                     # PathExpression_
   | expression '.' pathExprSegment '(' callParams? ')' # MethodCallExpression   // 8.2.10
   | expression '.' identifier                          # FieldExpression  // 8.2.11
   | expression '.' tupleIndex                          # TupleIndexingExpression   // 8.2.7
   ...
```
which makes it easy to implement any expression with precedence

**Comment by tomtau** [comment] 2022-07-14 00:41
duplicate of https://github.com/pest-parser/pest/issues/460

**Closed by tomtau** 2022-07-14 00:41 UTC
